In [1]:
plt = import '/matplotlib/pyplot'
pd = import '/pandas'
np = import '/numpy'
PolynomialFeatures = import '/sklearn/preprocessing/PolynomialFeatures'
LinearRegression = import '/sklearn/linear_model/LinearRegression'
train_test_split = import '/sklearn/model_selection/train_test_split' 

<function train_test_split at 0x147c95488>

In [2]:
veriseti = pd.read_table "https://gist.githubusercontent.com/LeaveNhA/6eaea566d9faf477205307446f43c3ff/raw/46fc24a48ac2c85f9c6f8e0858a1795fdf598d2c/hasta.data" sep:" "
X = np.array <| list <| map list <| map (bind take 3) veriseti.iloc

[[ 60 176  87]
 [ 53 167  86]
 [ 64 170 100]
 [ 37 173  79]
 [ 26 170  81]
 [ 61 165  92]
 [ 39 174  95]
 [ 28 171  68]
 [ 33 180  90]
 [ 39 166  74]
 [ 43 176  98]
 [ 42 172  53]
 [ 64 165  99]
 [ 64 164 112]
 [ 21 167  76]
 [ 57 168  96]
 [ 67 171  98]
 [ 60 172  80]
 [ 41 178  54]
 [ 71 175  89]
 [ 35 187  59]
 [ 58 170 104]
 [ 60 181  86]
 [ 64 179  90]
 [ 58 170  98]
 [ 63 170  82]
 [ 37 178  72]
 [ 28 175  71]
 [ 21 185  70]
 [ 54 173  93]
 [ 30 179  75]
 [ 20 173  75]
 [ 34 179  69]
 [ 19 176  77]
 [ 38 179  59]
 [ 65 174  94]
 [ 34 172  71]
 [ 34 182  63]
 [ 35 156  77]
 [ 58 168  93]
 [ 57 173  97]
 [ 37 173  83]
 [ 54 177  90]
 [ 65 179  90]
 [ 19 175  61]
 [ 68 168  86]
 [ 42 170  88]
 [ 28 169  96]
 [ 67 177 101]
 [ 29 172  62]
 [ 21 189  63]
 [ 19 178  70]
 [ 64 170  94]
 [ 67 166  89]
 [ 52 170  87]
 [ 30 170  74]
 [ 24 179  69]
 [ 49 168  96]
 [ 48 175  97]
 [ 37 191  92]
 [ 79 182 101]
 [ 51 174  82]
 [ 65 176  96]
 [ 60 172  93]
 [ 50 167  65]
 [ 59 163  76]
 [ 77 171 

In [3]:
y = veriseti !! 'KOLESTROL'
y.shape

(199,)

In [4]:
x = pd.DataFrame (np.array <| list <| map list' (veriseti !! 'KILO') (veriseti !! 'YAS')) columns:['KILO', 'YAS']
Y = y

0      395
1      350
2      304
3      178
4      206
      ... 
194    222
195    127
196    167
197    359
198    275
Name: KOLESTROL, Length: 199, dtype: int64

In [5]:
[x_eğitim, x_test, Y_eğitim, Y_test] = train_test_split x Y test_size:0.3 random_state:5

[     KILO  YAS
169    70   62
185    74   41
59     92   37
184    68   39
12     99   64
..    ...  ...
73     96   62
144   103   78
118    89   42
189    64   49
99     80   72

[139 rows x 2 columns],      KILO  YAS
119    68   62
77     91   54
148   110   60
149    60   37
154    73   38
151    71   22
122    72   67
6      95   39
28     70   21
71     87   65
187    73   35
34     59   38
21    104   58
40     97   57
55     74   30
104    84   52
3      79   37
39     93   58
117    64   36
134    98   67
179    76   48
26     72   37
54     87   52
164    79   19
53     89   67
93     80   39
173    81   20
17     80   60
56     69   24
84     69   32
25     82   63
156    88   69
42     90   54
141    92   29
50     63   21
51     70   19
194    57   35
116    64   39
142    71   66
24     98   58
159    82   46
62     96   65
165    70   21
45     86   68
23     90   64
1      86   53
162    67   34
48    101   67
160    86   58
126    72   49
123    99   62
107    79   37

In [6]:
#RNM{derece:degree}
#RNM{polinom_özellikleri:polinom_özellikler}
derece = 2
polinom_özellikleri = PolynomialFeatures degree:derece
x_eğitim_polinom = polinom_özellikleri.fit_transform x_eğitim

[[1.0000e+00 7.0000e+01 6.2000e+01 4.9000e+03 4.3400e+03 3.8440e+03]
 [1.0000e+00 7.4000e+01 4.1000e+01 5.4760e+03 3.0340e+03 1.6810e+03]
 [1.0000e+00 9.2000e+01 3.7000e+01 8.4640e+03 3.4040e+03 1.3690e+03]
 [1.0000e+00 6.8000e+01 3.9000e+01 4.6240e+03 2.6520e+03 1.5210e+03]
 [1.0000e+00 9.9000e+01 6.4000e+01 9.8010e+03 6.3360e+03 4.0960e+03]
 [1.0000e+00 8.6000e+01 4.2000e+01 7.3960e+03 3.6120e+03 1.7640e+03]
 [1.0000e+00 9.0000e+01 5.7000e+01 8.1000e+03 5.1300e+03 3.2490e+03]
 [1.0000e+00 6.3000e+01 1.9000e+01 3.9690e+03 1.1970e+03 3.6100e+02]
 [1.0000e+00 8.9000e+01 7.1000e+01 7.9210e+03 6.3190e+03 5.0410e+03]
 [1.0000e+00 9.6000e+01 4.9000e+01 9.2160e+03 4.7040e+03 2.4010e+03]
 [1.0000e+00 9.9000e+01 7.7000e+01 9.8010e+03 7.6230e+03 5.9290e+03]
 [1.0000e+00 6.4000e+01 4.4000e+01 4.0960e+03 2.8160e+03 1.9360e+03]
 [1.0000e+00 9.3000e+01 6.0000e+01 8.6490e+03 5.5800e+03 3.6000e+03]
 [1.0000e+00 7.5000e+01 4.1000e+01 5.6250e+03 3.0750e+03 1.6810e+03]
 [1.0000e+00 9.3000e+01 7.1000e+01

In [7]:
#NEW{Görünüşe göre SKLearn, get_feature_names işlevini `önerilmez` olarak işaretlemekte haklıymış
#    Şu anda, sütun isimleri gelmiyor. Sanırım sürüm farkı. ¯\_(ツ)_/¯ }

print polinom_özellikleri.get_feature_names!

['1', 'x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']



In [8]:
model = LinearRegression!
model.fit x_eğitim_polinom Y_eğitim

LinearRegression()

In [9]:
x_test_polinom = polinom_özellikleri.fit_transform x_test
"R-kare: {:.4f}".format $ model.score x_test_polinom Y_test

R-kare: 0.4920

In [10]:
print model.intercept_
print model.coef_

-276.2329106876422
[ 0.          7.47429078  3.2155489  -0.01395607 -0.06869892  0.05406707]



In [11]:
"Kolestrol= {:.3f} - {:.3f} * Kilo + {:.3f} * Yaş + {:.3f} * Kilo² - {:.3f} * (Kilo - Yaş) + {:.3f} * Yaş²".format model.intercept_ *: (tail model.coef_)

Kolestrol= -276.233 - 7.474 * Kilo + 3.216 * Yaş + -0.014 * Kilo² - -0.069 * (Kilo - Yaş) + 0.054 * Yaş²

In [13]:
#RNM{derece:degree}
#RNM{polinom_özellikleri_3d:polynominal_features}
#RNM{x_polinom:x_poly}
#EaV{z_surf: deterministik olan z işlevinin bir hesaplaması olarak açılmıştır, z(x_surf, y_surf)}

# 3D Hiperdüzlem Grafiği:
fig = plt.figure figsize:(18, 15)
ax = fig.add_subplot 111 projection:'3d'

ax.scatter (x !! 'KILO') (x !! 'YAS') Y c:'b'
ax.set_xlabel "Kilo"
ax.set_ylabel "Yaş"
ax.set_zlabel "Kolestrol"

# Kilo için:
x_surf = np.arange 0 120 5
# Yaş için:
y_surf = np.arange 0 80 5
[x_surf, y_surf] = np.meshgrid x_surf y_surf

# 2. Dereceden Polinom Regresyonu Eğitimi:
derece = 2
polinom_özellikleri_3d = PolynomialFeatures degree:derece
x_polinom = polinom_özellikleri_3d.fit_transform x

print "Öznitelikler:" $ polinom_özellikleri.get_feature_names!
    
# Doğrusal Regresyon Eğitimi:
model = LinearRegression!
model.fit x_polinom Y

# Eğitilen Modele Dayalı z(Kolestrol) Hesaplama:
# Referans için matematiksel modelin açıklaması, In[20]'ye danışabilirsiniz.
z = x_ y_ -> (map (*) (tail model.coef_) [x_, y_, x_ ** 2, x_ * y_, y_ ** 2]) |> sum |> (+ model.intercept_)

z_surf = z x_surf y_surf
ax.plot_surface x_surf y_surf z_surf rstride: 1 cstride: 1 color: 'NONE' alpha: 0.2

                
fig

Öznitelikler: ['1', 'x0', 'x1', 'x0^2', 'x0 x1', 'x1^2']

Figure(1800x1500)