In [1]:
# Bağımlılıkların enjeksiyonu:

In [2]:
except
    err_ => plt = import '/matplotlib/pyplot'
    
    err_ :: ModuleNotFoundError =>
            print "You need to install Matplotlib library by pip!"
            
    err_ is None => plt

<module 'matplotlib.pyplot' from '/Users/sckn/.pyenv/versions/3.6.15/lib/python3.6/site-packages/matplotlib/pyplot.py'>

In [3]:
except
    err_ => pd = import '/pandas'
    
    err_ :: ModuleNotFoundError =>
            print "You need to install Pandas library by pip!"
            
    err_ is None => pd

<module 'pandas' from '/Users/sckn/.pyenv/versions/3.6.15/lib/python3.6/site-packages/pandas/__init__.py'>

In [4]:
except
    err_ => np = import '/numpy'
    
    err_ :: ModuleNotFoundError =>
            print "You need to install Pandas library by pip!"
            
    err_ is None => np

<module 'numpy' from '/Users/sckn/.pyenv/versions/3.6.15/lib/python3.6/site-packages/numpy/__init__.py'>

In [5]:
veriseti = pd.read_table "https://gist.githubusercontent.com/LeaveNhA/6eaea566d9faf477205307446f43c3ff/raw/46fc24a48ac2c85f9c6f8e0858a1795fdf598d2c/hasta.data" sep:" "

     YAS  BOY  KILO  KOLESTROL SIGARA KAN_GRUBU    SONUC
0     60  176    87        395   EVET         B  POSITIF
1     53  167    86        350   EVET         o  POSITIF
2     64  170   100        304   EVET         A  POSITIF
3     37  173    79        178  HAYIR         o  NEGATIF
4     26  170    81        206  HAYIR         o  NEGATIF
..   ...  ...   ...        ...    ...       ...      ...
194   35  174    57        222  PASIF         A  NEGATIF
195   38  172    51        127  HAYIR         B  NEGATIF
196   26  170    60        167  HAYIR         A  NEGATIF
197   79  165    94        359   EVET         o  POSITIF
198   69  178    91        275   EVET         B  POSITIF

[199 rows x 7 columns]

In [6]:
veriseti.info!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199 entries, 0 to 198
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   YAS        199 non-null    int64 
 1   BOY        199 non-null    int64 
 2   KILO       199 non-null    int64 
 3   KOLESTROL  199 non-null    int64 
 4   SIGARA     199 non-null    object
 5   KAN_GRUBU  199 non-null    object
 6   SONUC      199 non-null    object
dtypes: int64(4), object(3)
memory usage: 11.0+ KB



In [7]:
veriseti.describe!

              YAS         BOY        KILO   KOLESTROL
count  199.000000  199.000000  199.000000  199.000000
mean    45.793970  172.306533   80.206030  243.412060
std     17.018195    6.763054   13.291706   85.675044
min     18.000000  156.000000   51.000000  107.000000
25%     32.500000  168.000000   70.000000  178.000000
50%     42.000000  172.000000   80.000000  225.000000
75%     61.500000  176.000000   91.000000  323.500000
max     79.000000  191.000000  112.000000  435.000000

In [8]:
except
    err_ => 
        linear_model = import '/sklearn/linear_model'
        train_test_split = import '/sklearn/model_selection/train_test_split'
        plt = import '/matplotlib/pyplot'
        ax = import '/matplotlib/axes'
        sns = import '/seaborn'
    err_ :: ModuleNotFoundError =>
            print "Kütüphane(ler) eksik, pip aracı ile yüklenmeliler!"
            
    err_ is None => [linear_model, train_test_split, plt, ax, sns]

[<module 'sklearn.linear_model' from '/Users/sckn/.pyenv/versions/3.6.15/lib/python3.6/site-packages/sklearn/linear_model/__init__.py'>, <function train_test_split at 0x147514c80>, <module 'matplotlib.pyplot' from '/Users/sckn/.pyenv/versions/3.6.15/lib/python3.6/site-packages/matplotlib/pyplot.py'>, <module 'matplotlib.axes' from '/Users/sckn/.pyenv/versions/3.6.15/lib/python3.6/site-packages/matplotlib/axes/__init__.py'>, <module 'seaborn' from '/Users/sckn/.pyenv/versions/3.6.15/lib/python3.6/site-packages/seaborn/__init__.py'>]

In [9]:
#NEW{Grafiklerde Izgara, grafik elemanlarının altında olmalı}

# Dökümanda belirtilmese de, Seaborn birçok yönetimsel işi yapıyor:
sns.set!

In [10]:
# X = df.iloc[:,: -1].values
#X = veriseti.iloc[:, 0:3].values
X = veriseti.values |> (bind map (bind take 3)) |> (bind map list) |> list |> np.array

[[ 60 176  87]
 [ 53 167  86]
 [ 64 170 100]
 [ 37 173  79]
 [ 26 170  81]
 [ 61 165  92]
 [ 39 174  95]
 [ 28 171  68]
 [ 33 180  90]
 [ 39 166  74]
 [ 43 176  98]
 [ 42 172  53]
 [ 64 165  99]
 [ 64 164 112]
 [ 21 167  76]
 [ 57 168  96]
 [ 67 171  98]
 [ 60 172  80]
 [ 41 178  54]
 [ 71 175  89]
 [ 35 187  59]
 [ 58 170 104]
 [ 60 181  86]
 [ 64 179  90]
 [ 58 170  98]
 [ 63 170  82]
 [ 37 178  72]
 [ 28 175  71]
 [ 21 185  70]
 [ 54 173  93]
 [ 30 179  75]
 [ 20 173  75]
 [ 34 179  69]
 [ 19 176  77]
 [ 38 179  59]
 [ 65 174  94]
 [ 34 172  71]
 [ 34 182  63]
 [ 35 156  77]
 [ 58 168  93]
 [ 57 173  97]
 [ 37 173  83]
 [ 54 177  90]
 [ 65 179  90]
 [ 19 175  61]
 [ 68 168  86]
 [ 42 170  88]
 [ 28 169  96]
 [ 67 177 101]
 [ 29 172  62]
 [ 21 189  63]
 [ 19 178  70]
 [ 64 170  94]
 [ 67 166  89]
 [ 52 170  87]
 [ 30 170  74]
 [ 24 179  69]
 [ 49 168  96]
 [ 48 175  97]
 [ 37 191  92]
 [ 79 182 101]
 [ 51 174  82]
 [ 65 176  96]
 [ 60 172  93]
 [ 50 167  65]
 [ 59 163  76]
 [ 77 171 

In [11]:
X.shape

(199, 3)

In [12]:
Y = veriseti.values |> (bind map (xs -> (xs |> drop 3 |> take 1))) |> (bind map list) |> list |> np.array
Y

[[395]
 [350]
 [304]
 [178]
 [206]
 [284]
 [232]
 [252]
 [359]
 [150]
 [380]
 [232]
 [337]
 [279]
 [268]
 [307]
 [222]
 [209]
 [195]
 [335]
 [132]
 [255]
 [393]
 [271]
 [360]
 [169]
 [120]
 [178]
 [154]
 [377]
 [225]
 [195]
 [114]
 [175]
 [107]
 [352]
 [117]
 [122]
 [134]
 [280]
 [366]
 [278]
 [285]
 [357]
 [195]
 [330]
 [218]
 [289]
 [258]
 [173]
 [138]
 [171]
 [356]
 [370]
 [250]
 [205]
 [178]
 [296]
 [152]
 [235]
 [435]
 [248]
 [397]
 [387]
 [140]
 [223]
 [330]
 [114]
 [133]
 [295]
 [240]
 [356]
 [307]
 [355]
 [145]
 [135]
 [354]
 [218]
 [176]
 [142]
 [154]
 [382]
 [175]
 [189]
 [217]
 [232]
 [123]
 [342]
 [147]
 [114]
 [178]
 [138]
 [346]
 [218]
 [236]
 [130]
 [201]
 [382]
 [300]
 [388]
 [239]
 [354]
 [200]
 [430]
 [227]
 [114]
 [385]
 [360]
 [290]
 [178]
 [334]
 [322]
 [297]
 [325]
 [119]
 [204]
 [118]
 [216]
 [228]
 [272]
 [367]
 [195]
 [264]
 [264]
 [280]
 [317]
 [144]
 [260]
 [204]
 [195]
 [140]
 [260]
 [195]
 [247]
 [394]
 [250]
 [129]
 [213]
 [226]
 [160]
 [203]
 [221]
 [264]

In [13]:
Y.shape

(199, 1)

In [14]:
# Kayıp gözlemi için:
veriseti |>.isnull! |>.sum!

YAS          0
BOY          0
KILO         0
KOLESTROL    0
SIGARA       0
KAN_GRUBU    0
SONUC        0
dtype: int64

In [15]:
# Özellik seçimi:
corr = veriseti.corr!
corr

                YAS       BOY      KILO  KOLESTROL
YAS        1.000000 -0.234608  0.604840   0.686904
BOY       -0.234608  1.000000 -0.023966  -0.163582
KILO       0.604840 -0.023966  1.000000   0.635008
KOLESTROL  0.686904 -0.163582  0.635008   1.000000

### Kolerasyon çıkarımı

<style>
table {float:left}
</style>

| | Yaş | Boy | Kilo |
| :--: | -------------: | ---: | --:|
| Korelasyon | 0.686904 | -0.163582 | 0.635008

In [16]:
# En yüksek kolerasyona sahip üç özelliği görmek için:
veriseti.corr! |>.abs! |>.nlargest 3 'KOLESTROL' |>.index

Index(['KOLESTROL', 'YAS', 'KILO'], dtype='object')

In [17]:
# Gözlem için Serpme Grafik:

fig = plt.figure figsize: (8, 5)

plt.scatter (veriseti !!'YAS') (veriseti !! 'KOLESTROL') marker:'o'
# X düzlem etiketi:
plt.xlabel 'Yaş'
# Y düzlem etiketi:
plt.ylabel 'Kolestrol'

fig

Figure(800x500)

In [18]:
# Gözlem için Serpme Grafik:

fig = plt.figure figsize: (8,5)

plt.scatter (veriseti !! 'KILO') (veriseti !! 'KOLESTROL') marker:'o'

# X düzlem etiketi:
plt.xlabel 'Kilo'
# Y düzlem etiketi:
plt.ylabel 'Kolestrol'

fig

Figure(800x500)

In [19]:
# Gözlem için Serpme Grafik:

fig = plt.figure figsize: (8,5)

plt.scatter (veriseti !! 'BOY') (veriseti !! 'KOLESTROL') marker:'o'

# X düzlem etiketi:
plt.xlabel 'Boy'
# Y düzlem etiketi:
plt.ylabel 'Kolestrol'

fig

Figure(800x500)

In [20]:
except
    err_ => Axes3D = import '/mpl_toolkits/mplot3d/Axes3D'
    
    err_ :: ModuleNotFoundError => 
            print 'Modül bulunamadı!'

<class 'mpl_toolkits.mplot3d.axes3d.Axes3D'>

In [21]:
#CHG{c='b': seaborn temalama işini devraldığı için, renklendirme argümanları gereksiz}
fig = plt.figure figsize:(10, 10)
#                    Boyut, Projeksiyon
ax = fig.add_subplot 111 projection:'3d'

ax.scatter (veriseti !! 'KILO') (veriseti !! 'YAS') (veriseti !! 'KOLESTROL') 

# Etiketler:
ax.set_xlabel "Kilo"
ax.set_ylabel "Yaş"
ax.set_zlabel "Kolestrol"

fig

Figure(1000x1000)

In [22]:
#NEW{Görünüşe göre SeaBorn değişiklik-geçmişi güzel tutulmuş. size parametresi, height olarak yeniden isimlendirildiği için aşağıdaki önlemler alındı.}
#NEW{Seaborn, figür erişimi, çıktının alınması için önemli.}

# Pairplot:
pairplot_ = sns.pairplot veriseti size:1.5

pairplot_.figure

Figure(600x600)

In [23]:
#NEW {numpy.c_, sadece basit bir fermuarlama (zip) operasyonu gibi duruyor. }

x = pd.DataFrame (zip (veriseti !! 'KILO') (veriseti !! 'YAS')) columns: ['Kilo', 'Yaş']
Y = veriseti !! 'KOLESTROL'

[x_train, x_test, Y_train, Y_test] = train_test_split x Y test_size:0.3 random_state:5

[     Kilo  Yaş
169    70   62
185    74   41
59     92   37
184    68   39
12     99   64
..    ...  ...
73     96   62
144   103   78
118    89   42
189    64   49
99     80   72

[139 rows x 2 columns],      Kilo  Yaş
119    68   62
77     91   54
148   110   60
149    60   37
154    73   38
151    71   22
122    72   67
6      95   39
28     70   21
71     87   65
187    73   35
34     59   38
21    104   58
40     97   57
55     74   30
104    84   52
3      79   37
39     93   58
117    64   36
134    98   67
179    76   48
26     72   37
54     87   52
164    79   19
53     89   67
93     80   39
173    81   20
17     80   60
56     69   24
84     69   32
25     82   63
156    88   69
42     90   54
141    92   29
50     63   21
51     70   19
194    57   35
116    64   39
142    71   66
24     98   58
159    82   46
62     96   65
165    70   21
45     86   68
23     90   64
1      86   53
162    67   34
48    101   67
160    86   58
126    72   49
123    99   62
107    79   37

In [24]:
# Gözlem için verilerin yapılarına bakıyoruz:
print $ "x_train.shape: {}.{n}Y_train: {}.".format x_train.shape Y_train.shape n:"\n"

print $ "x_test.shape: {}.{n}Y_test: {}.".format x_test.shape Y_test.shape n:"\n"

x_train.shape: (139, 2).
Y_train: (139,).
x_test.shape: (60, 2).
Y_test: (60,).



In [25]:
# Doğrusal regresyon için bağımlılık:
LinearRegression = import '/sklearn/linear_model/LinearRegression'

<class 'sklearn.linear_model._base.LinearRegression'>

In [26]:
model = LinearRegression!
model.fit x_train Y_train

LinearRegression()

In [27]:
kolestrol_tahmin = model.predict x_test

[261.11308626 290.40655819 347.05817403 179.41629314 210.18550023
 164.66644272 282.65774495 260.47458257 159.92373598 310.04320695
 202.46400508 179.82124983 328.89726043 311.14130351 191.76372153
 270.07676956 220.62491868 305.03963511 185.51796154 339.0484957
 242.43044247 205.44279348 276.58339465 174.2959478  319.52862044
 227.94145714 181.20752958 281.99192317 165.47635609 186.06700982
 294.05116837 322.50740884 288.23768316 228.22964033 144.74161078
 154.77607254 167.76200462 193.23945668 277.91503821 315.88401026
 250.29602921 329.56308221 159.92373598 315.59582707 313.97600032
 276.98835133 186.87692319 345.55512078 289.85750991 236.32877407
 328.34821215 220.62491868 316.54983203 146.10057243 251.10594258
 253.01395252 291.76551985 133.89723563 263.16518779 196.91138496]

In [28]:
"R-kare: {:.4f}".format $ model.score x_test Y_test

R-kare: 0.4755

In [29]:
# Metrikler için bağımlılık:
mean_squared_error = import '/sklearn/metrics/mean_squared_error'

mse = mean_squared_error Y_test kolestrol_tahmin
print mse

3163.6447982715777



In [30]:
# Bir de grafikle görelim:
figür = plt.figure!

plt.scatter Y_test kolestrol_tahmin
plt.xlabel "Gerçek Kolestrol"
plt.ylabel "Tahmini Kolestrol"
plt.title "Gerçek Kolestrol v Tahmin Edilen Kolestrol"

figür

Figure(640x480)

In [31]:
# Model katsayıları:
print model.intercept_
print model.coef_

-45.947982057770304
[2.16887503 2.57383172]



In [32]:
"Böylece model; `Kolestrol = {:.3f} + {:.3f} * Kilo + {:.3f} * Yaş` olarak ifade edilir.".format model.intercept_ (model.coef_ !! 0) (model.coef_ !! 1)

Böylece model; `Kolestrol = -45.948 + 2.169 * Kilo + 2.574 * Yaş` olarak ifade edilir.

In [33]:
#NEW{Öznitelik isimleri ile yürütülmesi gereken ifade, uyarıları bastırmak, örneğin bütünlüğü açısından en iyi yol:}

model.predict [[81, 55]]

[271.29163962]

In [34]:
# Kaynaklar:
# https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.scatter.html#matplotlib.axes.Axes.scatter
# https://seaborn.pydata.org/whatsnew.html