In [1]:
pd = import '/pandas'
plt = import '/matplotlib/pyplot'
mpatches = import '/matplotlib/patches'
load_breast_cancer = import '/sklearn/datasets/load_breast_cancer'

<function load_breast_cancer at 0x11ea88ae8>

In [2]:
#NEW {Lütfen, grafikleri gözlemlemek için aşağıdaki bayrağı aktif edin.}
# Yapılandırmalar:
showGraphicalContent = False

False

In [3]:
# Veri setini yükleme:
cancer = load_breast_cancer!

# Ortalama Textile
x = (map (!! 1) cancer.data) |> list
# 0: Kötü Huylu,
# 1: İyi Huylu:
y = cancer.target

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [4]:
#CHN {Python gerçeklemesinde önerdiğim şekilde,
#     edgecolors için daha öz bir hesaplama yapıyoruz.}

colors = {(0, 'red'), (1, 'blue')}
plt.scatter x y facecolors: 'none' edgecolors: ((map (x -> colors !! x) cancer.target) |> list) cmap: colors
plt.xlabel "Ortalama Texture"
plt.ylabel "Sonuç"

red = mpatches.Patch color: 'red' label: 'Kötü Huylu'
blue = mpatches.Patch color: 'blue' label: 'İyi Huylu'
plt.legend handles: [red, blue] loc: 1

showGraphicalContent and plt.show!

False

In [5]:
#CHN {linear_model nesnesinin bir kez kullanımı üzerine, kullanımı elemine etmek için çağrımı ekleme
#    kütüphanenin eklenmesi ifadesinde çözümledik}
#ADD{Numpy kütüphanesinin çağırımsız kullanımını düzeltmek için, deklarasyon yapıldı}

LogisticRegression = import '/sklearn/linear_model/LogisticRegression'
np = import '/numpy'

<module 'numpy' from '/Users/sckn/.pyenv/versions/3.6.15/lib/python3.6/site-packages/numpy/__init__.py'>

In [6]:
#RNM {log_regress:lojistik_regresyon}

lojistik_regresyon = LogisticRegression!
#np.array(x).reshape(len(x), 1),
lojistik_regresyon.fit X: ((np.array x) |>.reshape (len x) 1) y: y

LogisticRegression()

In [7]:
print lojistik_regresyon.intercept_
print lojistik_regresyon.coef_

[5.12260029]
[[-0.23448037]]



In [8]:
sigmoid = x ->
        1 / (1 + (np.exp (- ((lojistik_regresyon.intercept_ !! 0) + ((lojistik_regresyon.coef_ |> (!! 0) |> (!! 0)) * x)))))

<function sigmoid at 0x15f442048>

In [9]:
x1 = np.arange 0 30 0.01
y1 = (map sigmoid x1) |> list

[0.9940748133827558, 0.9940609862916314, 0.9940471271266572, 0.9940332358143364, 0.9940193122810083, 0.9940053564528468, 0.9939913682558615, 0.993977347615897, 0.9939632944586312, 0.9939492087095776, 0.9939350902940823, 0.9939209391373252, 0.9939067551643188, 0.9938925382999088, 0.9938782884687728, 0.9938640055954205, 0.9938496896041933, 0.9938353404192639, 0.9938209579646352, 0.9938065421641417, 0.9937920929414469, 0.9937776102200454, 0.9937630939232601, 0.9937485439742435, 0.9937339602959772, 0.9937193428112703, 0.9937046914427607, 0.9936900061129136, 0.9936752867440217, 0.9936605332582042, 0.9936457455774074, 0.9936309236234036, 0.9936160673177905, 0.9936011765819921, 0.993586251337257, 0.9935712915046585, 0.9935562970050945, 0.9935412677592866, 0.9935262036877808, 0.9935111047109452, 0.9934959707489718, 0.9934808017218745, 0.9934655975494897, 0.9934503581514753, 0.9934350834473115, 0.9934197733562978, 0.9934044277975564, 0.993389046690028, 0.9933736299524747, 0.9933581775034768, 0.

In [10]:
plt.scatter x y facecolors: 'none' edgecolors: ((map (x -> colors !! x) cancer.target) |> list) cmap: colors
plt.plot x1 y1
plt.xlabel "Ortalama Texture"
plt.ylabel "Olasılık"

showGraphicalContent and plt.show!

False

In [11]:
#SUG{np.array([30]).reshape(1, 1):[[30]], double question-mark (??)}

# ____$'dan sonrasını parantez içinde hayal edin.
print $ lojistik_regresyon.predict_proba [[30]]
print $ lojistik_regresyon.predict [[30]]

[[0.87122245 0.12877755]]
[0]



In [12]:
#SUG{np.array([10]).reshape(1, 1):[[10]], double question-mark (??)}

# Yukarıdaki gibi,
# ____$'dan sonrasını parantez içinde hayal edin.
print $ lojistik_regresyon.predict_proba [[10]]
print $ lojistik_regresyon.predict [[10]]

[[0.05853587 0.94146413]]
[1]



In [13]:
# Daha fazla özellik kullanarak modeli eğitmek için;
# eğitim seti için, veri setinin %80'i hedef değişkene göre rastgele seçilirse:

train_test_split = import '/sklearn/model_selection/train_test_split'
LinearRegression = import '/sklearn/linear_model/LinearRegression'
metrics = import '/sklearn/metrics'

<module 'sklearn.metrics' from '/Users/sckn/.pyenv/versions/3.6.15/lib/python3.6/site-packages/sklearn/metrics/__init__.py'>

In [14]:
#RNM{train_set:eğitim_seti}
#RNM{test_set:test_seti}
#RNM{train_labels:eğitim_etiketleri}
#RNM{test_labels:test_etiketleri}

[eğitim_seti, test_seti, eğitim_etiketleri, test_etiketleri] =
    # ____________________________________________________________ hedef değişkene göre tesadüfilik:
    train_test_split cancer.data cancer.target test_size: 0.2 random_state: 1 stratify: cancer.target

[array([[1.422e+01, 2.312e+01, 9.437e+01, ..., 1.772e-01, 5.166e-01,
        1.446e-01],
       [1.846e+01, 1.852e+01, 1.211e+02, ..., 1.642e-01, 3.695e-01,
        8.579e-02],
       [1.340e+01, 2.052e+01, 8.864e+01, ..., 2.051e-01, 3.585e-01,
        1.109e-01],
       ...,
       [1.152e+01, 1.493e+01, 7.387e+01, ..., 9.608e-02, 2.664e-01,
        7.809e-02],
       [1.218e+01, 1.408e+01, 7.725e+01, ..., 1.852e-02, 2.293e-01,
        6.037e-02],
       [1.919e+01, 1.594e+01, 1.263e+02, ..., 1.777e-01, 2.443e-01,
        6.251e-02]]), array([[1.371e+01, 1.868e+01, 8.873e+01, ..., 1.284e-01, 2.849e-01,
        9.031e-02],
       [1.624e+01, 1.877e+01, 1.088e+02, ..., 1.732e-01, 2.770e-01,
        1.063e-01],
       [1.163e+01, 2.929e+01, 7.487e+01, ..., 6.835e-02, 2.884e-01,
        7.220e-02],
       ...,
       [1.719e+01, 2.207e+01, 1.116e+02, ..., 1.984e-01, 3.216e-01,
        7.570e-02],
       [1.831e+01, 1.858e+01, 1.186e+02, ..., 1.571e-01, 3.206e-01,
        6.938e-02],
     

In [15]:
#RNM{log_regress:lojistik_regresyon_hdg, lojist_regresyon önceden tanımlı,
#    bir son-ek ile yeniden tanımlandı.}
#NEW{Görünüşe göre, Lojistik Regresyon sürecindeki varsayılan çözümleyici (hesaplayıcı, algoritma)
#    Limited-memory Broyden–Fletcher–Goldfarb–Shanno Algorithm (lbfgs), total iterasyon limitine
#    takılıyor. Varsayılan maksimum iterasyon değerini (100), 2500 olarak tanımlandı.

# İlk on (10) özellik seçimi:
x = (map (i -> take 30 i) eğitim_seti) |> (bind map list) |> list
# 0: Kötü Huylu,
# 1: İyi Huylu:
y = eğitim_etiketleri
# Hedef değişkene göre (hdg), Lojistik Regresyon değişkeni:
lojistik_regresyon_hdg = LogisticRegression max_iter: 2500
lojistik_regresyon_hdg.fit X: x y: y

LogisticRegression(max_iter=2500)

In [16]:
print lojistik_regresyon_hdg.intercept_
print lojistik_regresyon_hdg.coef_

[35.75236948]
[[ 0.89910365  0.19953176 -0.35301804  0.03193124 -0.13088869 -0.19637684
  -0.44327392 -0.24317193 -0.23468656 -0.02464939 -0.12876275  0.89073982
   0.5576907  -0.15531508 -0.01768398  0.02757701 -0.03937877 -0.03478448
  -0.03674257  0.00164348 -0.04193034 -0.41835611 -0.15197106 -0.00991119
  -0.27715402 -0.70447342 -1.21617963 -0.52331131 -0.71399133 -0.09778556]]



In [17]:
#CHN{Panda, Notdefterine önceden eklendiği için yeniden içerleme yapılmadı.}
#RNM{preds_proba:tahmin_olasılıkları}
#RNM{preds_class:tahmin_sınıfları}
#RNM{original_result:orijinal_sonuçlar}
#RNM{result:sonuç}

tahmin_olasılıkları = pd.DataFrame $ lojistik_regresyon_hdg.predict_proba X: test_seti
tahmin_olasılıkları.columns = ["Malignant", "Benign"]

tahminler = lojistik_regresyon_hdg.predict X: test_seti
tahmin_sınıfları = pd.DataFrame tahminler
tahmin_sınıfları.columns = ["Tahmin"]

orijinal_sonuçlar = pd.DataFrame test_etiketleri
orijinal_sonuçlar.columns = ["Orijinal Sonuç"]

#Üç veri çerçevesini 1 veri çerçevesine indirgeme:
sonuç = pd.concat [tahmin_olasılıkları, tahmin_sınıfları, orijinal_sonuçlar] axis: 1
print $ sonuç.head 15

    Malignant        Benign  Tahmin  Orijinal Sonuç
0    0.063909  9.360908e-01       1               1
1    0.955738  4.426206e-02       0               0
2    0.068295  9.317053e-01       1               1
3    0.000502  9.994983e-01       1               1
4    0.999978  2.229047e-05       0               0
5    0.004134  9.958661e-01       1               1
6    0.005241  9.947593e-01       1               1
7    0.005547  9.944527e-01       1               1
8    1.000000  5.478683e-10       0               0
9    0.000614  9.993858e-01       1               1
10   0.092594  9.074059e-01       1               0
11   0.015449  9.845513e-01       1               1
12   0.000011  9.999888e-01       1               1
13   0.135334  8.646659e-01       1               0
14   0.008156  9.918443e-01       1               1



In [18]:
print "----Karışıklık Matrisi----"
print $ pd.crosstab tahminler test_etiketleri

----Karışıklık Matrisi----
col_0   0   1
row_0        
0      38   1
1       4  71



In [19]:
print '----Doğruluk (Accuracy)----'
print $ lojistik_regresyon_hdg.score X: test_seti y: test_etiketleri

----Doğruluk (Accuracy)----
0.956140350877193



In [20]:
#NEW{Başlık ortalandı.}

print "         ----------Metriksler----------         "
print $
    metrics.classification_report y_true: test_etiketleri y_pred: tahminler

         ----------Metriksler----------         
              precision    recall  f1-score   support

           0       0.97      0.90      0.94        42
           1       0.95      0.99      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114




In [21]:
#AUC ÖRNEĞİ***
#NEW{Örneğe bağlı temel değişkenler bu örnekten çıkarılacak.
#    Tahmin_olasılıkları_ ve tahminler_ değerleri örnek özelinde,
#    önceden elde ettiğimiz tahmin nesnesi üzerinden oluşturulmuştur.

tahmin_olasılıkları_ = lojistik_regresyon_hdg.predict_proba X: test_seti
tahminler_ = (map (i -> take 1 i) tahmin_olasılıkları_) |> map list |> map np.array |> list

[fpr, tpr, threshold] = metrics.roc_curve test_etiketleri tahminler_

(array([0.        , 0.02380952, 0.88095238, 0.88095238, 0.9047619 ,
       0.9047619 , 0.92857143, 0.92857143, 0.95238095, 0.95238095,
       1.        , 1.        ]), array([0.        , 0.        , 0.        , 0.01388889, 0.01388889,
       0.02777778, 0.02777778, 0.05555556, 0.05555556, 0.06944444,
       0.06944444, 1.        ]), array([2.00000000e+00, 1.00000000e+00, 9.41799271e-01, 9.16193200e-01,
       6.05801644e-01, 3.12054258e-01, 2.49873640e-01, 1.51929769e-01,
       1.35334145e-01, 1.10255814e-01, 9.25940891e-02, 8.96126999e-08]))

In [26]:
roc_auc = metrics.auc fpr tpr

0.005621693121693121

In [29]:
#ADD {OZ_, sabiti tekrarlı sihirli değer kullanımını azaltmak için oluşturuldu.}
OZ_ = [0, 1]

plt.plot fpr tpr 'b' label: ("Eğri Altında Kalan Alan (AUC) = {:.2f}".format roc_auc)
plt.plot OZ_ OZ_ 'r--'
plt.xlim OZ_
plt.ylim OZ_
plt.xlabel "Yanlış Pozitif Oranı (YPO)"
plt.ylabel "Gerçek Pozitif Oranı (GPO)"
plt.title "Alıcı Karakteristikler Operatörü (ROC)"
plt.legend loc: 'lower right'

showGraphicalContent and plt.show!

False

In [30]:
# KAYNAK
# https://stackoverflow.com/questions/38640109/logistic-regression-python-solvers-definitions/52388406#52388406