In [1]:
except
    err_ =>
        PolynomialFeatures = import '/sklearn/preprocessing/PolynomialFeatures'
        np = import '/numpy'
    err_ :: ModuleNotFoundError =>
            print 'Modül yüklü değil.'

<module 'numpy' from '/Users/sckn/.pyenv/versions/3.6.15/lib/python3.6/site-packages/numpy/__init__.py'>

In [2]:
#RNM{degree->derece}
derece = 2
polinom_özellikleri = PolynomialFeatures degree: derece

PolynomialFeatures()

In [3]:
#NEW{x: 1..10, **(] => vektör vektörü}
x = (range 1 10) |> (bind map list') |> list |> np.array
x_polinom = polinom_özellikleri.fit_transform x

[[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]
 [ 1.  5. 25.]
 [ 1.  6. 36.]
 [ 1.  7. 49.]
 [ 1.  8. 64.]
 [ 1.  9. 81.]]

In [4]:
#NEW{Ödevin Python versiyonunda sürüm farkından dolayı alınan hata, burada alınmıyor.
#    get_feature_names geçerli sürüm ağı (diğer paketlerle oluşan versiyon koleksiyonu)
#    için uygun ve kullanılıyor.}

print $ polinom_özellikleri.get_feature_names 'x'

['1', 'x', 'x^2']



In [5]:
#NEW{Örnekte bağımlılık ele alınmamış}
#WRN{Seaborn önerilmeyen olarak işaretlenmiş bir bağımlılık barındırıyor.}

except
    err_ =>
        LinearRegression = import '/sklearn.linear_model/LinearRegression'
        plt = import '/matplotlib/pyplot'
        ax = import '/matplotlib/axes'
        sns = import '/seaborn'
        sns.set!
    err_ :: ModuleNotFoundError =>
            print "Modül(ler) yüklü değil!"

In [6]:
#NEW{y:[[1], [3], [5], [6], [6], [8], [8], [7], [7]], örnek grafikten çıkarımlanmıştır. Yanlışlanabilir.}
y = [[1], [3], [5], [6], [6], [8], [8], [7], [7]]
model = LinearRegression!
model.fit x_polinom y
y_polinom_tahmin = model.predict x_polinom
#SPC{Doge gerçeklemesine özel, figürü almalıyız. Diğer ödevleri okuduysanız aşinasınızdır artık.}
figür = plt.figure!
# Noktaların grafiği:
plt.scatter x y s: 10
# Regresyon doğrusu:
plt.plot x y_polinom_tahmin color: 'r'
    
figür

Figure(640x480)

In [7]:
print model.intercept_
print model.coef_

[-1.33333333]
[[ 0.          2.55151515 -0.18181818]]



In [8]:
"Böylece model; `Y = {:.2f} + {:.3f}x {:.4f}x²` olarak ifade edilir.".format (model.intercept_ !! 0) *:(model.coef_ |> head |> tail |> list)

Böylece model; `Y = -1.33 + 2.552x -0.1818x²` olarak ifade edilir.

In [9]:
"Eğitim seti için R-kare: {:.4f}".format $ model.score x_polinom y

Eğitim seti için R-kare: 0.9647

In [10]:
#Kaynaklar:
# https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.FeatureUnion.html#sklearn.pipeline.FeatureUnion.get_feature_names_out
# https://matplotlib.org/3.5.0/api/_as_gen/matplotlib.pyplot.scatter.html, argüman listesi incelendi, y çıkarımı yapıldı.